#!/bin/bash

# Layout
yabai -m config layout bsp
yabai -m config window_gap 4
yabai -m config top_padding 4
yabai -m config bottom_padding 4
yabai -m config left_padding 4
yabai -m config right_padding 4

# Focus
yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_follows_focus off

# Mouse drag (Linux style)
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
